Repository vmware/terraform-provider-tanzu-mission-control, pull requests merged in 2022-11, with the labels that each got.

#87 Documentation and resource templates for credential resource
  docs/data-sources/credential.md
  docs/resources/credential.md
  examples/resources/credential/aws_eks.tf
  examples/resources/credential/cluster_image_registry_config.tf
  examples/resources/credential/cluster_proxy.tf
  examples/resources/credential/dataprotection.tf
  resource_templates/credential_aws_eks.tf
  resource_templates/credential_dataprotection.tf
  resource_templates/credential_image_registry.tf
  resource_templates/credential_proxy.tf
  resource_templates/credential_tanzu_observability.tf
  templates/data-sources/credential.md.tmpl
  templates/resources/credential.md.tmpl
Labels: documentation

#86 Implementation of TMC credential resource with acceptance test and documentation
  Makefile
  docs/data-sources/credential.md
  docs/resources/credential.md
  examples/data-sources/credential/data-source.tf
  examples/resources/credential/aws_eks.tf
  examples/resources/credential/cluster_image_registry_config.tf
  examples/resources/credential/cluster_proxy.tf
  examples/resources/credential/dataprotection.tf
  examples/resources/credential/taznu_observability.tf
  internal/client/credential/credentials_resource.go
  internal/client/http_client.go
  internal/models/credential/aws_spec.go
  internal/models/credential/credentials.go
  internal/models/credential/request.go
  internal/models/credential/spec.go
  internal/models/credential/spec_data.go
  internal/models/credential/status.go
  internal/provider/provider.go
  internal/resources/cluster/data_source_cluster.go
  internal/resources/cluster/nodepools/resource_node_pool.go
  internal/resources/cluster/resource_cluster.go
  internal/resources/clustergroup/data_source_cluster_group.go
  internal/resources/clustergroup/resource_cluster_group.go
  internal/resources/common/objectmeta_schema.go
  internal/resources/credential/aws_cred.go
  internal/resources/credential/constants.go
  internal/resources/credential/credential.go
  internal/resources/credential/credential_provider_test.go
  internal/resources/credential/data_source_credential_test.go
  internal/resources/credential/datasource_credential.go
  internal/resources/credential/key_value.go
  internal/resources/credential/mapping.go
  internal/resources/credential/resource_credential_test.go
  internal/resources/iampolicy/resource_iam_policy.go
  internal/resources/namespace/data_source_namespace.go
  internal/resources/namespace/resource_namespace.go
  internal/resources/policy/type/security/resource_security_policy.go
  internal/resources/workspace/data_source_workspace.go
  internal/resources/workspace/resource_workspace.go
  resource_templates/credential_aws_eks.tf
  resource_templates/credential_dataprotection.tf
  resource_templates/credential_image_registry.tf
  resource_templates/credential_proxy.tf
  resource_templates/credential_tanzu_observability.tf
  templates/data-sources/credential.md.tmpl
  templates/resources/credential.md.tmpl
Labels: dco-required

#88 Add proxy support and related documentation to terraform provider
  docs/guides/provider_behind_proxy.md
  docs/index.md
  examples/proxy/provider.tf
  examples/proxy/variables.tf
  internal/authctx/authentication.go
  internal/authctx/client.go
  internal/authctx/constants.go
  internal/authctx/helper.go
  internal/client/http_client.go
  internal/client/proxy/testdata/ca.crt
  internal/client/proxy/testdata/client.crt
  internal/client/proxy/testdata/client.key
  internal/client/proxy/testdata/invalid_ca.crt
  internal/client/proxy/testdata/invalid_client.crt
  internal/client/proxy/testdata/invalid_client.key
  internal/client/proxy/tls.go
  internal/client/proxy/tls_test.go
  internal/client/transport/client.go
  internal/client/transport/methods_test.go
  templates/guides/provider_behind_proxy.md.tmpl
Labels: enhancement

#78 Implement TSM Integration Resource
  .golangci.yml
  Makefile
  examples/data-sources/integration/data-source.tf
  examples/resources/integration/resource_integration_tsm.tf
  go.mod
  internal/client/http_client.go
  internal/client/integration/integration_resource.go
  internal/models/cluster/extension/health.go
  internal/models/cluster/extension/phase.go
  internal/models/cluster/integration/create_integration_request.go
  internal/models/cluster/integration/create_integration_response.go
  internal/models/cluster/integration/delete_integration_response.go
  internal/models/cluster/integration/full_name.go
  internal/models/cluster/integration/get_integration_response.go
  internal/models/cluster/integration/indicator.go
  internal/models/cluster/integration/integration.go
  internal/models/cluster/integration/operator.go
  internal/models/cluster/integration/phase.go
  internal/models/cluster/integration/spec.go
  internal/models/cluster/integration/status.go
  internal/models/cluster/integration/update_integration_response.go
  internal/models/cluster/integration/workload.go
  internal/models/organization/integration/phase.go
  internal/provider/provider.go
  internal/resources/cluster/integration/constant.go
  internal/resources/cluster/integration/data_source_integration.go
  internal/resources/cluster/integration/data_source_integration_test.go
  internal/resources/cluster/integration/default_integration_client.go
  internal/resources/cluster/integration/resource_integration.go
  internal/resources/cluster/integration/resource_integration_helper.go
  internal/resources/cluster/integration/resource_integration_helper_test.go
  internal/resources/cluster/integration/resource_integration_spec.go
  internal/resources/cluster/integration/resource_integration_spec_test.go
  internal/resources/cluster/integration/resource_integration_test.go
Labels: cla-not-required

#96 Correct resource templates for security policy resource and format the examples and templates
  examples/resources/security_policy/resource_cluster_custom_security_policy.tf
  examples/resources/security_policy/resource_cluster_group_baseline_security_policy.tf
  examples/resources/security_policy/resource_cluster_group_custom_security_policy.tf
  examples/resources/security_policy/resource_cluster_strict_security_policy.tf
  examples/resources/security_policy/resource_organization_custom_security_policy.tf
  examples/resources/security_policy/resource_organization_strict_security_policy.tf
  resource_templates/cluster_group_scoped_baseline_security_policy.tf
  resource_templates/cluster_group_scoped_custom_security_policy.tf
  resource_templates/cluster_group_scoped_strict_security_policy.tf
  resource_templates/cluster_scoped_baseline_security_policy.tf
  resource_templates/cluster_scoped_custom_security_policy.tf
  resource_templates/cluster_scoped_strict_security_policy.tf
  resource_templates/credential_aws_eks.tf
  resource_templates/credential_dataprotection.tf
  resource_templates/credential_image_registry.tf
  resource_templates/credential_proxy.tf
  resource_templates/credential_tanzu_observability.tf
  resource_templates/organization_scoped_baseline_security_policy.tf
  resource_templates/organization_scoped_custom_security_policy.tf
  resource_templates/organization_scoped_strict_security_policy.tf
Labels: documentation

#97 Documentation for Tanzu Service Mesh Integration
  docs/data-sources/integration.md
  docs/resources/integration.md
  docs/resources/security_policy.md
  examples/data-sources/integration/data-source.tf
  examples/resources/integration/resource.tf
  examples/resources/integration/resource_integration_tsm.tf
  resource_templates/tsm-integration.tf
  templates/data-sources/integration.md.tmpl
  templates/resources/integration.md.tmpl
Labels: documentation
