Repository vmware/terraform-provider-tanzu-mission-control, pull requests merged in 2023-04, with the labels that each got.

#140 Add read context for data source handler function for differentiating between different read calls
  internal/helper/handler_context.go
  internal/resources/cluster/nodepools/data_source_node_pool.go
  internal/resources/cluster/nodepools/resource_node_pool.go
  internal/resources/clustergroup/data_source_cluster_group.go
  internal/resources/credential/datasource_credential.go
  internal/resources/credential/resource_credential.go
  internal/resources/namespace/data_source_namespace.go
  internal/resources/workspace/data_source_workspace.go
Labels: enhancement

#147 Add kubeconfig validation checks to create operation instead of schema validation to handle external module referencing cases
  internal/resources/cluster/data_source_cluster.go
  internal/resources/cluster/resource_cluster.go
Labels: bug

#132 Add Acceptance tests and documentation for kubernetes secret resource and data source
  docs/data-sources/kubernetes_secret.md
  docs/resources/kubernetes_secret.md
  examples/data-sources/kubernetes_secret/data-source.tf
  examples/resources/kubernetes_secret/resource.tf
  internal/helper/helper.go
  internal/resources/kubernetessecret/data_source_secret.go
  internal/resources/kubernetessecret/data_source_secret_test.go
  internal/resources/kubernetessecret/resource_helper_test.go
  internal/resources/kubernetessecret/resource_secret.go
  internal/resources/kubernetessecret/resource_secret_test.go
  internal/resources/kubernetessecret/secret_provider_test.go
  templates/data-sources/kubernetes_secret.md.tmpl
  templates/resources/kubernetes_secret.md.tmpl
Labels: dco-required
