Repository vmware/terraform-provider-tanzu-mission-control, pull requests merged in 2024-11, with the labels that each got.

#424 chore: add codeowners
  CODEOWNERS
Labels: chore

#423 chore(gh): add dependabot
  .github/dependabot.yml
Labels: dependencies, chore, github-actions

#326 docs: update akscluster
  docs/guides/tanzu-mission-control_akscluster.md
Labels: documentation

#436 chore(ci): add codeql analysis
  .github/workflows/codeql-analysis.yml
Labels: dependencies, chore, github-actions, needs-review, technical-debt

#449 chore: update `NOTICE`
  NOTICE
Labels: chore

#446 chore: add issue templates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: chore, needs-review

#447 chore: update `.gitignore`
  .gitignore
Labels: chore, needs-review

#448 chore: update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/pull_request_templace.md
Labels: chore, needs-review

#451 chore(gh): add lock threads
  .github/workflows/lock.yml
Labels: chore, github-actions, needs-review

#453 chore: update code of conduct
  CODE_OF_CONDUCT.md
Labels: chore, needs-review

#452 chore(gh): add stale workflow
  .github/workflows/stale.yml
Labels: chore, github-actions, needs-review

#454 chore(gh): add issue labels
  .github/labeler-issues.yml
  .github/workflows/issues.yml
Labels: chore, github-actions, needs-review

#456 docs: add install, build, and test docs
  README.md
  docs/build.md
  docs/images/icon-color.svg
  docs/install.md
  docs/test.md
Labels: documentation, needs-review

#435 chore(gh): update golangci-lint workflow
  .github/workflows/golangci-lint.yml
  .golangci.yml
Labels: chore, github-actions, needs-review, technical-debt
