Repository vmware/terraform-provider-tanzu-mission-control, pull requests merged in 2024-12, with the labels that each got.

#467 fix: incorrect conversion between integer types
  internal/resources/tanzupackageinstall/spec/cluster_scope.go
Labels: bug, provider, needs-review, technical-debt

#462 chore(deps): bump go from 1.19 to 1.23.2
  README.md
  go.mod
  go.sum
Labels: documentation, dependencies, chore, provider, needs-review

#475 Remove TSM integration support
  .github/workflows/release.yml
  .github/workflows/test.yml
  Makefile
  docs/data-sources/integration.md
  docs/resources/integration.md
  examples/data-sources/integration/data-source.tf
  examples/resources/integration/resource.tf
  internal/client/http_client.go
  internal/client/integration/integration_resource.go
  internal/models/cluster/integration/create_integration_request.go
  internal/models/cluster/integration/create_integration_response.go
  internal/models/cluster/integration/delete_integration_response.go
  internal/models/cluster/integration/full_name.go
  internal/models/cluster/integration/get_integration_response.go
  internal/models/cluster/integration/indicator.go
  internal/models/cluster/integration/integration.go
  internal/models/cluster/integration/operator.go
  internal/models/cluster/integration/phase.go
  internal/models/cluster/integration/spec.go
  internal/models/cluster/integration/status.go
  internal/models/cluster/integration/update_integration_response.go
  internal/models/cluster/integration/workload.go
  internal/models/organization/integration/phase.go
  internal/provider/provider.go
  internal/resources/cluster/integration/constant.go
  internal/resources/cluster/integration/data_source_integration.go
  internal/resources/cluster/integration/data_source_integration_test.go
  internal/resources/cluster/integration/default_integration_client.go
  internal/resources/cluster/integration/resource_integration.go
  internal/resources/cluster/integration/resource_integration_helper.go
  internal/resources/cluster/integration/resource_integration_helper_test.go
  internal/resources/cluster/integration/resource_integration_spec.go
  internal/resources/cluster/integration/resource_integration_spec_test.go
  internal/resources/cluster/integration/resource_integration_test.go
  resource_templates/tsm-integration.tf
  templates/data-sources/integration.md.tmpl
  templates/resources/integration.md.tmpl
Labels: documentation, chore, provider, github-actions, breaking-change, needs-review

#481 chore: fix linter issues
  .golangci.yml
  internal/client/proxy/tls_test.go
  internal/client/transport/methods_test.go
  internal/helper/helper.go
  internal/helper/retry.go
  internal/resources/akscluster/resource_akscluster_test.go
  internal/resources/cluster/tkgaws/resource_tkg_aws.go
  internal/resources/clusterclass/datasource_cluster_class.go
  internal/resources/ekscluster/ekscluster_flatten_test.go
  internal/resources/ekscluster/helpers_test.go
  internal/resources/gitrepository/data_source_git_repository.go
  internal/resources/gitrepository/resource_git_repository.go
  internal/resources/helmcharts/helm_charts_mock_test.go
  internal/resources/helmfeature/data_source_helm_feature.go
  internal/resources/helmrelease/data_source_helm_release.go
  internal/resources/helmrelease/resource_helm_release.go
  internal/resources/helmrepository/helm_repository_data_source.go
  internal/resources/helmrepository/helm_repository_mock_test.go
  internal/resources/iampolicy/resource_iam_policy.go
  internal/resources/kustomization/resource_kustomization.go
  internal/resources/permissiontemplate/datasource_permission_template.go
  internal/resources/permissiontemplate/schema.go
  internal/resources/policy/kind/network/recipe/custom_common_schema.go
  internal/resources/policy/kind/network/recipe/custom_egress_schema.go
  internal/resources/policy/kind/network/recipe/custom_ingress_schema.go
  internal/resources/policy/operations/update.go
  internal/resources/provisioner/data_source_provisioner.go
  internal/resources/sourcesecret/resource_sourcesecret.go
  internal/resources/tanzukubernetescluster/helper.go
  internal/resources/tanzukubernetescluster/resource_tanzu_kuberenetes_cluster.go
  internal/resources/tanzupackageinstall/spec/cluster_scope.go
  internal/resources/tanzupackagerepository/resource_package_repository.go
Labels: chore, provider, needs-review

#463 bug: fix for eks cluster and nodepool tag issue
  internal/resources/ekscluster/resource_ekscluster.go
Labels: bug, dco-required, provider, needs-review

#484 chore(tests): fix subnet values for EKS cluster and nodepools
  internal/resources/ekscluster/resource_ekscluster_test.go
Labels: provider, needs-review

#485 chore(tests): update test config
  internal/resources/testing/test_config.go
Labels: provider, needs-review

#486 chore(tests): update AKS cluster version in tests
  internal/models/akscluster/network_config.go
  internal/resources/akscluster/akscluster_mapper.go
  internal/resources/akscluster/constants.go
  internal/resources/akscluster/helpers_test.go
  internal/resources/akscluster/resource_akscluster_acc_test.go
  internal/resources/akscluster/schema.go
Labels: provider, needs-review
