Repository vmware/terraform-provider-tanzu-mission-control, pull requests merged in 2025-03, with the labels that each got.

#488 Control plane overrides for VKS 3.2
  docs/data-sources/tanzu_kubernetes_cluster.md
  docs/resources/tanzu_kubernetes_cluster.md
  internal/models/tanzukubernetescluster/control_plane.go
  internal/resources/tanzukubernetescluster/converter_mapping.go
  internal/resources/tanzukubernetescluster/helper.go
  internal/resources/tanzukubernetescluster/resource_tanzu_kuberenetes_cluster.go
  internal/resources/tanzukubernetescluster/schema.go
  internal/resources/tanzukubernetescluster/tests/cluster_env_vars.go
  internal/resources/tanzukubernetescluster/tests/resource_tf_configs.go
Labels: documentation, provider, needs-review

#479 fixing datasource schema for tanzu kubernetes clusters and adding generic helper
  .gitignore
  Makefile
  internal/helper/helper.go
  internal/resources/tanzukubernetescluster/data_source.go
  main.go
Labels: chore, provider, needs-review

#529 chore(release): v1.4.9
  CHANGELOG.md
Labels: documentation
